### ISSUE TITLE
Замечания по 1.1

### ISSUE THREAD

**Issue by sergey-shambir** [Lena2112/laboratory1#1]
- папка  Debug не должна быть под контролем версий Git
- [Объявлять константы через define не следует](http://stackoverflow.com/questions/1674032/) - `#define g 9.8f`
- зачем передавать параметры по константному значению, если вызывающему всё равно, будет изменяться скопированное на стек значение или нет, поскольку он сам никогда не воспользуется копией?

``` cpp
void DisplayStateAtTheMoment(const float currentTimePoint, const float v0);
void OutputOnDisplay(const float timeWhenTheMaximumHeight);
```
- за что отвечает эта переменная? `bool flag = false;`
- данное выражение всегда истинно, потому что int в принципе не может хранить значений больших, чем INT_MAX: `theMaximumJumpHeight < INT_MAX`
- лучше убрать функцию PpressingExpectation, если пользователю потребуется, он запустить программу из эмулятора консоли; ожидание действий пользователя (причём только в некоторых ситуациях) затрудняет написание скриптов, использующих программу в автоматическом режиме

**Comment by sergey-shambir** [comment]
5 из 10

**Comment by Lena2112** [comment]
@sergey-shambir , замечания устранены.

**Comment by sergey-shambir** [comment]
Вместо `static const float g = 9.8f;` можно было бы использовать название GRAVITY. Тем не менее, 10 из 10.
