### ISSUE TITLE
Замечания по 1.2 (clocks)

### ISSUE THREAD

**Issue by sergey-shambir** [Lena2112/laboratory1#2]
- файл `clock.vcxproj.user` содержит локальные настройки пользователя и не должен быть под контролем версий Git
- не надо объявлять две переменных в одной строке, не надо разделять инициализацию и объявление `float x, y;`
- в названии positionText порядок слов, видимо, неправильный, читается как "текст позиции"
- в функции ProcessMainLoop рисование всех элементов лучше выделить в отдельную функцию

**Comment by sergey-shambir** [comment]
8 из 10

**Comment by Lena2112** [comment]
@sergey-shambir , замечания устранены.

**Comment by sergey-shambir** [comment]
10 из 10
